AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  ApplicationS3Bucket:
   Description: Provide your bucket name
   Type: String
   Default: bucketname
  ApplicationS3Artifact:
   Description: Provide your application code zip or war
   Type: String
   Default: xxxxxx.zip
  VPCId:
   Type: AWS::EC2::VPC::Id
  AppSubnet1:
   Type: AWS::EC2::Subnet::Id
   Description: Select the subnet for EB instance in different Availability Zones!
  AppSubnet2:
   Type: AWS::EC2::Subnet::Id
   Description: Select the subnet for EB instance in different Availability Zones!
  ElbSubnets:
   Type: List<AWS::EC2::Subnet::Id>
   Description: Select two subnets in different Availability Zones! for ELB
  EbInstanceType:
    Description: The instance type for Elastic Beanstalk
    Type: String
    Default: t2.micro
    ConstraintDescription: Instance type not supported
    AllowedValues:
      - t2.micro 
      - t2.small
      - t2.medium
      - t2.large
      - t2.xlarge
      - t2.2xlarge
      - m5.large
      - m5.xlarge
      - m5.2xlarge
      - m5.4xlarge
      - m5.12xlarge
      - m5.24xlarge
      - r4.large
      - r4.xlarge
      - r4.2xlarge
      - r4.4xlarge
      - r4.8xlarge
      - r4.16xlarge

  EC2KeyName:
   Description: The EC2 Key Pair to use for the Atlas/WebAPI EC2 Instances.
   Type: AWS::EC2::KeyPair::KeyName
  RollingUpdateEnabled:
   Type: String
   Description: select true/false for rolling updates
   AllowedValues:
     - 'true'
     - 'false'
   Default: 'true'
  Applicationame:
   Type: String
   Description: 'Name of the ElasticBeanstalk Application'
  LoadBalancerScheme:
   Description: Indicates whether the load balancer in front of the Ec2 service is internet-facing or internal.
   Type: String
   AllowedValues:
     - 'internet-facing'
     - internal 
  EnvName:
    Description: Enter the Environment Name
    Type: String 
  SslCertificate:
    Description: Enter the ACM Arn
    Type: String

 

##Environment variables Parameters for WP-config.php
#  RDSUserName: 
#    NoEcho: true  
#    Description: Enter the Db RDS_USERNAME
#    Type: String
#  RDSDbName: 
#    NoEcho: true    
#    Description: Enter the Db RDS Db Name
#    Type: String
#  RDSDbPassword:
#    NoEcho: true   
#    Description: Enter the Db RDS Db Password
#    Type: String
#  RDSEndPoint:
#    NoEcho: true   
#    Description: Enter the Db RDS End Point
#    Type: String

##Environment variables Parameters for EFS
  FileSytemId:   
    Description: Enter the FILE_SYSTEM_ID
    Type: String
  Region:   
    Description: Enter the Region
    Type: String
  MountDirectory:   
    Description: Enter the MOUNT_DIRECTORY For Efs
    Type: String


Resources:
  EBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security Group for EC2 to allow SSH from Bastion and expose HTTP 80
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '80'
          ToPort: '80'
          SourceSecurityGroupId: !Ref ALBSecurityGroup
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'   
          SourceSecurityGroupId: !Ref ALBSecurityGroup
      VpcId: !Ref VPCId
      Tags: 
       - Key: Name 
         Value: !Sub ${AWS::StackName}-EbSg
  ALBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SecurityGroup for ElasticBeanstalk Balancer
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '80'
        ToPort: '80'
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: '443'
        ToPort: '443'
        CidrIp: 0.0.0.0/0
      VpcId: !Ref VPCId
      Tags: 
       - Key: Name 
         Value: !Sub ${AWS::StackName}-AlbSg
  wordpressApp:
    Type: AWS::ElasticBeanstalk::Application
    Properties:
      ApplicationName: !Ref Applicationame
      Description: AWS Elastic Beanstalk Sample Application
  wordpressAppVersion:
    Type: AWS::ElasticBeanstalk::ApplicationVersion
    Properties:
      ApplicationName:
        Ref: wordpressApp
      Description: AWS ElasticBeanstalk Sample Application Version
      SourceBundle:
        S3Bucket: !Ref ApplicationS3Bucket
        S3Key: !Ref ApplicationS3Artifact 
  wordpressconfig:
    Type: AWS::ElasticBeanstalk::ConfigurationTemplate
    Properties:
      ApplicationName:
        Ref: wordpressApp
      Description: AWS ElasticBeanstalk Sample Configuration Template
      OptionSettings:
      - Namespace: aws:autoscaling:asg
        OptionName: MinSize
        Value: '1'
      - Namespace: aws:autoscaling:asg
        OptionName: MaxSize
        Value: '6'
      - Namespace: aws:elasticbeanstalk:environment
        OptionName: EnvironmentType
        Value: LoadBalanced
      - Namespace: aws:elasticbeanstalk:environment
        OptionName: LoadBalancerType
        Value: application
      - Namespace: aws:elbv2:listener:default
        OptionName: ListenerEnabled
        Value: 'true'
      - Namespace: aws:autoscaling:launchconfiguration
        OptionName: EC2KeyName
        Value: !Ref EC2KeyName
      - Namespace: aws:autoscaling:trigger
        OptionName: MeasureName
        Value: CPUUtilization
      - Namespace: aws:ec2:vpc
        OptionName: VPCId
        Value: !Ref VPCId   
      - Namespace: aws:ec2:vpc
        OptionName: Subnets
        Value: !Ref AppSubnet1
      - Namespace: aws:ec2:vpc
        OptionName: Subnets
        Value: !Ref AppSubnet2  
      - Namespace: aws:ec2:vpc
        OptionName: ELBSubnets
        Value: !Join [",", [!Select [0, !Ref ElbSubnets], !Select [1, !Ref ElbSubnets]]]
      - Namespace: aws:autoscaling:launchconfiguration
        OptionName: InstanceType
        Value: !Ref EbInstanceType
#      - Namespace: aws:elasticbeanstalk:environment:process:default
#        OptionName: Port
#        Value: 80
      - Namespace: aws:elasticbeanstalk:environment:process:default
        OptionName: Protocol
        Value: HTTP
#      - Namespace: aws:ec2:vpc
#        OptionName: AssociatePublicIpAddress
#        Value: 'true'
      - Namespace: aws:autoscaling:launchconfiguration
        OptionName: SecurityGroups
        Value: !Ref EBSecurityGroup
      - Namespace: aws:elb:loadbalancer 
        OptionName: SecurityGroups
        Value: !Ref ALBSecurityGroup
      - Namespace: aws:ec2:vpc
        OptionName: ELBScheme
        Value: !Ref LoadBalancerScheme
      - Namespace: aws:autoscaling:launchconfiguration
        OptionName: IamInstanceProfile
        Value: aws-elasticbeanstalk-ec2-role

## Https 443 with ACM 
#      - Namespace: aws:elbv2:listener:443
#        OptionName: DefaultProcess
#        Value: https
#      - Namespace: aws:elbv2:listener:443
#        OptionName: Protocol
#        Value: HTTPS
#      - Namespace: aws:elbv2:listener:443
#        OptionName: SSLCertificateArns
#        Value: !Ref SslCertificate
#      - Namespace: aws:elasticbeanstalk:environment:process:https
#        OptionName: Port
#        Value: 443
#      - Namespace: aws:elasticbeanstalk:environment:process:https
#        OptionName: Protocol
#        Value: HTTPS          
#      - Namespace: aws:elasticbeanstalk:environment:process:https
#        OptionName: StickinessEnabled
#        Value: true   
      

##EB RDS environment variables
#      - Namespace: aws:elasticbeanstalk:application:environment
#        OptionName: RDS_USERNAME
#        Value: !Ref RDSUserName
#      - Namespace: aws:elasticbeanstalk:application:environment
#        OptionName: RDS_PASSWORD
#        Value: !Ref RDSDbPassword
#      - Namespace: aws:elasticbeanstalk:application:environment
#        OptionName: RDS_DB_NAME
#        Value: !Ref RDSDbName
#      - Namespace: aws:elasticbeanstalk:application:environment
#        OptionName:  RDS_PORT
#        Value: 3306
#      - Namespace: aws:elasticbeanstalk:application:environment
#        OptionName:  RDS_HOSTNAME
#        Value: !Ref RDSEndPoint  
        

##EB EFS environment variables  
      - Namespace: aws:elasticbeanstalk:application:environment
        OptionName: FILE_SYSTEM_ID
        Value: !Ref FileSytemId
      - Namespace: aws:elasticbeanstalk:application:environment
        OptionName: REGION
        Value: !Ref Region 
      - Namespace: aws:elasticbeanstalk:application:environment
        OptionName: MOUNT_DIRECTORY
        Value: !Ref MountDirectory
      SolutionStackName: 64bit Amazon Linux 2018.03 v2.9.0 running PHP 7.3
  sampleEnvironment:
    Type: AWS::ElasticBeanstalk::Environment
    Properties:
      ApplicationName:
        Ref: wordpressApp
      Description: AWS ElasticBeanstalk Sample Environment
      EnvironmentName: !Ref EnvName
      TemplateName:
        Ref: wordpressconfig
      VersionLabel:
        Ref: wordpressAppVersion
